### ISSUE TITLE
Faraday gem dependency

### ISSUE THREAD

**Issue by matiasmasca** [sequenia/Pushkin#1]
Hi,
I want to inform to you that there are a problem with the Faraday gem reference, in order to get it work I had to add the gem in my gemfile. 

```
gem 'pushkin-library'
gem 'faraday', '~> 0.15.4'
```
Because when I tried to send a message I received an error message about "Pushkin NameError: uninitialized constant Pushkin::Fcm::SendFcmPushService::Faraday" 

PD: great work with your gem =D

**Comment by 4ybakut2004** [comment]
@matiasmasca Thanks for the feedback!

We will add the Faraday to the Pushkin's dependency in the next version of the Gem.
(Or even replace the Faraday by the native Net::HTTP).

I'm very glad that you are using our gem and that you liked it =)
